title: Sapna Maduraimuthu
remote_theme:  pages-themes/leap-day@v0.2.0
lang: en-US
branch: main
navbar-col: "#ccccff"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#ccccff"
text-col: "#FFFFE0"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"



